/**
 * Kotlin code generator for the RPC bridge framework.
 *
 * Generates idiomatic Kotlin data classes with kotlinx-serialization-protobuf
 * annotations, service interfaces, and dispatcher classes from parsed .proto
 * file definitions.
 */

import type {
  ProtoFile,
  MessageDef,
  FieldDef,
  EnumDef,
  ServiceDef,
} from './parser.js';

// ---------------------------------------------------------------------------
// Proto-to-Kotlin type mapping
// ---------------------------------------------------------------------------

const PROTO_TO_KOTLIN: Record<string, string> = {
  string: 'String',
  bool: 'Boolean',
  bytes: 'ByteArray',
  int32: 'Int',
  int64: 'Long',
  uint32: 'UInt',
  uint64: 'ULong',
  sint32: 'Int',
  sint64: 'Long',
  fixed32: 'UInt',
  fixed64: 'ULong',
  sfixed32: 'Int',
  sfixed64: 'Long',
  float: 'Float',
  double: 'Double',
};

function kotlinType(protoType: string): string {
  return PROTO_TO_KOTLIN[protoType] ?? protoType;
}

function kotlinFieldType(field: FieldDef, allEnums: EnumDef[]): string {
  const base = kotlinType(field.type);
  if (field.repeated) return `List<${base}>`;
  if (field.optional) return `${base}?`;
  return base;
}

function defaultValue(field: FieldDef, allEnums: EnumDef[]): string {
  if (field.repeated) return 'emptyList()';
  if (field.optional) return 'null';
  const kt = kotlinType(field.type);
  switch (kt) {
    case 'String': return '""';
    case 'Boolean': return 'false';
    case 'ByteArray': return 'ByteArray(0)';
    case 'Int': return '0';
    case 'Long': return '0L';
    case 'UInt': return '0u';
    case 'ULong': return '0uL';
    case 'Float': return '0.0f';
    case 'Double': return '0.0';
    default:
      if (allEnums.some((e) => e.name === field.type)) {
        return `${kt}.fromValue(0)`;
      }
      return `${kt}()`;
  }
}

function camelCase(name: string): string {
  return name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function lowerFirst(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

export function generateKotlin(proto: ProtoFile): string {
  const lines: string[] = [];
  const indent = (n: number) => '    '.repeat(n);

  function emit(depth: number, line: string) {
    if (line === '') {
      lines.push('');
    } else {
      lines.push(`${indent(depth)}${line}`);
    }
  }

  // File header
  emit(0, '@file:OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)');
  emit(0, '');
  emit(0, '// -----------------------------------------------------------------');
  emit(0, '// GENERATED CODE - DO NOT EDIT');
  emit(0, '//');
  emit(0, '// Generated by rpc-concept codegen from a .proto definition.');
  emit(0, '// Any manual changes will be overwritten on next generation.');
  emit(0, '// -----------------------------------------------------------------');
  emit(0, '');

  // Package
  if (proto.package) {
    emit(0, `package ${proto.package}`);
    emit(0, '');
  }

  // Imports
  emit(0, 'import com.rpcbridge.DispatchResult');
  emit(0, 'import com.rpcbridge.ServiceDispatcher');
  emit(0, 'import kotlinx.coroutines.flow.Flow');
  emit(0, 'import kotlinx.coroutines.flow.first');
  emit(0, 'import kotlinx.coroutines.flow.map');
  emit(0, 'import kotlinx.serialization.Serializable');
  emit(0, 'import kotlinx.serialization.protobuf.ProtoBuf');
  emit(0, 'import kotlinx.serialization.protobuf.ProtoNumber');
  emit(0, '');

  // Enums
  for (const enumDef of proto.enums) {
    emitEnum(emit, enumDef);
  }

  // Messages
  for (const msg of proto.messages) {
    emitMessage(emit, msg, proto.enums);
  }

  // Services
  for (const svc of proto.services) {
    emitServiceInterface(emit, svc);
    emitDispatcher(emit, svc, proto.package);
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Enum generation
// ---------------------------------------------------------------------------

function emitEnum(emit: (depth: number, line: string) => void, enumDef: EnumDef) {
  emit(0, `enum class ${enumDef.name}(val value: Int) {`);
  for (let i = 0; i < enumDef.values.length; i++) {
    const v = enumDef.values[i];
    const suffix = i < enumDef.values.length - 1 ? ',' : ';';
    emit(1, `${v.name}(${v.number})${suffix}`);
  }
  emit(0, '');
  emit(1, 'companion object {');
  emit(2, `fun fromValue(value: Int): ${enumDef.name} =`);
  emit(3, `entries.firstOrNull { it.value == value } ?: ${enumDef.values[0]?.name ?? 'throw IllegalArgumentException("Unknown enum value: $value")'}`);
  emit(1, '}');
  emit(0, '}');
  emit(0, '');
}

// ---------------------------------------------------------------------------
// Message data class generation (using kotlinx-serialization-protobuf)
// ---------------------------------------------------------------------------

function emitMessage(
  emit: (depth: number, line: string) => void,
  msg: MessageDef,
  allEnums: EnumDef[],
) {
  const fields = msg.fields;

  emit(0, '@Serializable');
  if (fields.length === 0) {
    emit(0, `data class ${msg.name}(val _unused: Byte = 0) {`);
  } else {
    emit(0, `data class ${msg.name}(`);
    for (let i = 0; i < fields.length; i++) {
      const f = fields[i];
      const ktName = camelCase(f.name);
      const ktType = kotlinFieldType(f, allEnums);
      const defVal = defaultValue(f, allEnums);
      const comma = i < fields.length - 1 ? ',' : '';
      const deprecation = f.deprecated ? '@Deprecated("Field is deprecated") ' : '';
      emit(1, `${deprecation}@ProtoNumber(${f.number}) val ${ktName}: ${ktType} = ${defVal}${comma}`);
    }
    emit(0, ') {');
  }

  // encode()
  emit(0, '');
  emit(1, 'fun encode(): ByteArray = ProtoBuf.encodeToByteArray(this)');

  // companion object with decode()
  emit(0, '');
  emit(1, 'companion object {');
  emit(2, `fun decode(data: ByteArray): ${msg.name} = ProtoBuf.decodeFromByteArray(data)`);
  emit(1, '}');
  emit(0, '}');
  emit(0, '');
}

// ---------------------------------------------------------------------------
// Service interface generation
// ---------------------------------------------------------------------------

function emitServiceInterface(
  emit: (depth: number, line: string) => void,
  svc: ServiceDef,
) {
  emit(0, `interface ${svc.name} {`);
  for (const m of svc.methods) {
    emit(0, '');
    const reqType = kotlinType(m.inputType);
    const respType = kotlinType(m.outputType);

    if (!m.clientStreaming && !m.serverStreaming) {
      // Unary
      emit(1, `suspend fun ${lowerFirst(m.name)}(request: ${reqType}): ${respType}`);
    } else if (!m.clientStreaming && m.serverStreaming) {
      // Server streaming
      emit(1, `fun ${lowerFirst(m.name)}(request: ${reqType}): Flow<${respType}>`);
    } else if (m.clientStreaming && !m.serverStreaming) {
      // Client streaming
      emit(1, `suspend fun ${lowerFirst(m.name)}(requests: Flow<${reqType}>): ${respType}`);
    } else {
      // Bidi streaming
      emit(1, `fun ${lowerFirst(m.name)}(requests: Flow<${reqType}>): Flow<${respType}>`);
    }
  }
  emit(0, '}');
  emit(0, '');
}

// ---------------------------------------------------------------------------
// Dispatcher generation
// ---------------------------------------------------------------------------

function emitDispatcher(
  emit: (depth: number, line: string) => void,
  svc: ServiceDef,
  pkg: string,
) {
  const dispatcherName = `${svc.name}Dispatcher`;
  const serviceQualifier = pkg ? `${pkg}.${svc.name}` : svc.name;

  emit(0, `class ${dispatcherName}(private val service: ${svc.name}) : ServiceDispatcher {`);
  emit(0, '');
  emit(1, `override val serviceName = "${serviceQualifier}"`);
  emit(0, '');
  emit(1, 'override suspend fun dispatch(method: String, messages: Flow<ByteArray>): DispatchResult {');
  emit(2, 'return when (method) {');

  for (const m of svc.methods) {
    const methodFullName = `"${serviceQualifier}/${m.name}"`;
    const reqType = kotlinType(m.inputType);
    const methodName = lowerFirst(m.name);

    if (!m.clientStreaming && !m.serverStreaming) {
      // Unary
      emit(3, `${methodFullName} -> {`);
      emit(4, `val request = ${reqType}.decode(messages.first())`);
      emit(4, `val response = service.${methodName}(request)`);
      emit(4, 'DispatchResult.Unary(response.encode())');
      emit(3, '}');
    } else if (!m.clientStreaming && m.serverStreaming) {
      // Server streaming
      emit(3, `${methodFullName} -> {`);
      emit(4, `val request = ${reqType}.decode(messages.first())`);
      emit(4, `val responseFlow = service.${methodName}(request)`);
      emit(4, 'DispatchResult.Stream(responseFlow.map { it.encode() })');
      emit(3, '}');
    } else if (m.clientStreaming && !m.serverStreaming) {
      // Client streaming
      emit(3, `${methodFullName} -> {`);
      emit(4, `val typedStream = messages.map { ${reqType}.decode(it) }`);
      emit(4, `val response = service.${methodName}(typedStream)`);
      emit(4, 'DispatchResult.Unary(response.encode())');
      emit(3, '}');
    } else {
      // Bidi streaming
      emit(3, `${methodFullName} -> {`);
      emit(4, `val typedStream = messages.map { ${reqType}.decode(it) }`);
      emit(4, `val responseFlow = service.${methodName}(typedStream)`);
      emit(4, 'DispatchResult.Stream(responseFlow.map { it.encode() })');
      emit(3, '}');
    }
  }

  emit(3, 'else -> throw IllegalArgumentException("Unknown method: $method")');
  emit(2, '}');
  emit(1, '}');
  emit(0, '}');
  emit(0, '');
}
