/**
 * Swift code generator for the RPC bridge framework.
 *
 * Generates Codable enums, message structs, service provider protocols with
 * async/await, and dispatcher classes that route JSON data to typed handler
 * methods. No external dependencies beyond Foundation and RpcBridge.
 *
 * Two modes:
 * - Service protos (has services): wraps types in a namespace enum, imports RpcBridge
 * - Framework protos (no services): emits top-level types, no RpcBridge import
 */

import type {
  ProtoFile,
  MessageDef,
  EnumDef,
  ServiceDef,
} from './parser.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function generateSwift(proto: ProtoFile): string {
  const lines: string[] = [];
  const emit = (line = '') => lines.push(line);
  const emitBlock = (block: string) => {
    for (const l of block.split('\n')) lines.push(l);
  };

  const hasServices = proto.services.length > 0;
  const namespace = swiftNamespace(proto.package);

  // File header
  emit('// DO NOT EDIT.');
  emit(`// Generated by rpc-bridge-codegen from package "${proto.package}".`);
  emit('// Any manual changes will be overwritten on the next generation run.');
  emit('');
  emit('import Foundation');
  if (hasServices) emit('import RpcBridge');
  emit('');

  // Collect enum names so we can detect enum-typed fields
  const enumNames = new Set(proto.enums.map((e) => e.name));

  if (hasServices) {
    // Service proto: wrap everything in a namespace enum
    emit(`// MARK: - ${namespace}`);
    emit('');
    emit(`public enum ${namespace} {`);

    for (const enumDef of proto.enums) {
      emit('');
      emitBlock(indent(generateEnum(enumDef), 1));
    }
    for (const msg of proto.messages) {
      emit('');
      emitBlock(indent(generateMessageStruct(msg, enumNames, proto.messages), 1));
    }
    emit('');
    emitBlock(indent(generateDispatchError(), 1));
    for (const svc of proto.services) {
      emit('');
      emitBlock(indent(generateServiceProtocol(svc, proto), 1));
      emit('');
      emitBlock(indent(generateDispatcher(svc, proto), 1));
    }
    emit('}');
  } else {
    // Framework proto: emit top-level types (no namespace, no RpcBridge import)
    for (const enumDef of proto.enums) {
      emit('');
      emitBlock(generateEnum(enumDef));
    }
    for (const msg of proto.messages) {
      emit('');
      emitBlock(generateMessageStruct(msg, enumNames, proto.messages));
    }
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Naming helpers
// ---------------------------------------------------------------------------

/** Convert a proto package like "demo.hello.v1" to "DemoHelloV1". */
function swiftNamespace(pkg: string): string {
  return pkg.split('.').map((s) => s.charAt(0).toUpperCase() + s.slice(1)).join('');
}

/** Convert snake_case to camelCase. */
function snakeToCamel(name: string): string {
  return name.replace(/_([a-z])/g, (_, ch) => ch.toUpperCase());
}

/** Convert a proto method name (PascalCase) to Swift camelCase. */
function swiftMethodName(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

const SWIFT_KEYWORDS = new Set([
  'associatedtype', 'class', 'deinit', 'enum', 'extension', 'fileprivate',
  'func', 'import', 'init', 'inout', 'internal', 'let', 'open', 'operator',
  'private', 'protocol', 'public', 'rethrows', 'static', 'struct',
  'subscript', 'typealias', 'var', 'break', 'case', 'continue', 'default',
  'defer', 'do', 'else', 'fallthrough', 'for', 'guard', 'if', 'in',
  'repeat', 'return', 'switch', 'where', 'while', 'as', 'catch', 'false',
  'is', 'nil', 'super', 'self', 'Self', 'throw', 'throws', 'true', 'try',
  'Type', 'Protocol',
]);

/** Escape Swift keywords with backticks. */
function escapeSwiftKeyword(name: string): string {
  return SWIFT_KEYWORDS.has(name) ? `\`${name}\`` : name;
}

/** Resolve a proto type reference to the short name used inside the namespace enum. */
function resolveTypeName(protoType: string, proto: ProtoFile): string {
  const pkg = proto.package;
  if (protoType.startsWith(pkg + '.')) return protoType.slice(pkg.length + 1);
  return protoType;
}

/**
 * Derive the enum value prefix to strip from proto enum values.
 * e.g. "FrameType" -> "FRAME_TYPE_"
 */
function enumPrefix(enumName: string): string {
  // Convert PascalCase to SCREAMING_SNAKE_CASE, then add trailing underscore
  const snake = enumName.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
  return snake + '_';
}

/**
 * Convert a proto enum value name to a Swift case name.
 * e.g. "FRAME_TYPE_HALF_CLOSE" with prefix "FRAME_TYPE_" -> "halfClose"
 */
function enumCaseName(valueName: string, prefix: string): string {
  const stripped = valueName.startsWith(prefix) ? valueName.slice(prefix.length) : valueName;
  // SCREAMING_SNAKE -> camelCase
  return stripped.toLowerCase().replace(/_([a-z])/g, (_, ch) => ch.toUpperCase());
}

// ---------------------------------------------------------------------------
// Proto type -> Swift type mapping
// ---------------------------------------------------------------------------

function swiftType(protoType: string, enumNames: Set<string>): string {
  switch (protoType) {
    case 'string': return 'String';
    case 'bytes': return 'AnyCodable';
    case 'bool': return 'Bool';
    case 'uint32': case 'fixed32': return 'UInt32';
    case 'int32': case 'sint32': case 'sfixed32': return 'Int32';
    case 'uint64': case 'fixed64': return 'UInt64';
    case 'int64': case 'sint64': case 'sfixed64': return 'Int64';
    case 'float': return 'Float';
    case 'double': return 'Double';
    default:
      if (enumNames.has(protoType)) return protoType;
      return protoType; // message type reference
  }
}

function swiftDefault(protoType: string, enumNames: Set<string>): string {
  switch (protoType) {
    case 'string': return '""';
    case 'bytes': return 'nil';
    case 'bool': return 'false';
    case 'uint32': case 'fixed32':
    case 'int32': case 'sint32': case 'sfixed32':
    case 'uint64': case 'fixed64':
    case 'int64': case 'sint64': case 'sfixed64':
    case 'float': case 'double':
      return '0';
    default:
      if (enumNames.has(protoType)) return `.${enumCaseName('UNSPECIFIED', '')}`;
      return `${protoType}()`;
  }
}

/** True if this field type is optional (nil when absent from JSON). */
function isOptionalField(protoType: string): boolean {
  return protoType === 'bytes';
}

/** True if this proto type needs string encoding in JSON (uint64/int64). */
function isStringEncodedInJSON(protoType: string): boolean {
  return ['uint64', 'int64', 'sint64', 'fixed64', 'sfixed64'].includes(protoType);
}

// ---------------------------------------------------------------------------
// Enum generation
// ---------------------------------------------------------------------------

function generateEnum(enumDef: EnumDef): string {
  const lines: string[] = [];
  const prefix = enumPrefix(enumDef.name);

  lines.push(`public enum ${enumDef.name}: UInt32, Codable, Sendable {`);
  for (const v of enumDef.values) {
    const caseName = enumCaseName(v.name, prefix);
    lines.push(`    case ${caseName} = ${v.number}`);
  }
  lines.push('}');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Message struct generation
// ---------------------------------------------------------------------------

function generateMessageStruct(msg: MessageDef, enumNames: Set<string>, allMessages: MessageDef[] = []): string {
  if (msg.oneofs.length > 0) {
    return generateOneofMessageStruct(msg, enumNames, allMessages);
  }

  const lines: string[] = [];

  lines.push(`public struct ${msg.name}: Codable, Sendable {`);

  // Properties
  for (const f of msg.fields) {
    const camel = snakeToCamel(f.name);
    const prop = escapeSwiftKeyword(camel);
    const isOpt = isOptionalField(f.type);
    const base = swiftType(f.type, enumNames);
    const type = f.repeated ? `[${base}]` : (isOpt ? `${base}?` : base);
    const def = f.repeated ? '[]' : swiftDefault(f.type, enumNames);
    lines.push(`    public var ${prop}: ${type} = ${def}`);
  }

  // Default init
  lines.push('');
  lines.push('    public init() {}');

  // CodingKeys (always generated for proto3 JSON compatibility)
  if (msg.fields.length > 0) {
    lines.push('');
    lines.push('    enum CodingKeys: String, CodingKey {');
    for (const f of msg.fields) {
      const camel = snakeToCamel(f.name);
      const key = escapeSwiftKeyword(camel);
      lines.push(`        case ${key}`);
    }
    lines.push('    }');
  }

  // Custom decoder: always generated so missing keys get proto3 defaults
  if (msg.fields.length > 0) {
    lines.push('');
    lines.push('    public init(from decoder: Decoder) throws {');
    lines.push('        let container = try decoder.container(keyedBy: CodingKeys.self)');
    for (const f of msg.fields) {
      const camel = snakeToCamel(f.name);
      const prop = escapeSwiftKeyword(camel);
      const key = escapeSwiftKeyword(camel);
      const st = swiftType(f.type, enumNames);

      if (f.repeated) {
        lines.push(`        self.${prop} = (try? container.decode([${st}].self, forKey: .${key})) ?? []`);
      } else if (isOptionalField(f.type)) {
        lines.push(`        self.${prop} = try? container.decode(${st}.self, forKey: .${key})`);
      } else if (isStringEncodedInJSON(f.type)) {
        lines.push(`        if let v = try? container.decode(${st}.self, forKey: .${key}) {`);
        lines.push(`            self.${prop} = v`);
        lines.push(`        } else if let s = try? container.decode(String.self, forKey: .${key}), let v = ${st}(s) {`);
        lines.push(`            self.${prop} = v`);
        lines.push('        }');
      } else if (enumNames.has(f.type)) {
        lines.push(`        self.${prop} = (try? container.decode(${st}.self, forKey: .${key})) ?? ${swiftDefault(f.type, enumNames)}`);
      } else if (f.repeated) {
        lines.push(`        self.${prop} = (try? container.decode([${st}].self, forKey: .${key})) ?? []`);
      } else {
        lines.push(`        self.${prop} = (try? container.decode(${st}.self, forKey: .${key})) ?? ${swiftDefault(f.type, enumNames)}`);
      }
    }
    lines.push('    }');
  }

  // JSON Data helpers (used by dispatchers)
  lines.push('');
  lines.push('    public init(jsonUTF8Data data: Data) throws {');
  lines.push('        self = try JSONDecoder().decode(Self.self, from: data)');
  lines.push('    }');
  lines.push('');
  lines.push('    public func jsonUTF8Data() throws -> Data {');
  lines.push('        return try JSONEncoder().encode(self)');
  lines.push('    }');

  lines.push('}');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Oneof message struct generation
// ---------------------------------------------------------------------------

/**
 * Generate a Swift struct for a message that contains a `oneof`.
 * Produces a companion enum for the body, plus custom Codable on the struct
 * that encodes/decodes each variant as a separate JSON key.
 */
function generateOneofMessageStruct(
  msg: MessageDef,
  enumNames: Set<string>,
  allMessages: MessageDef[],
): string {
  const lines: string[] = [];
  const oo = msg.oneofs[0]; // support the first oneof (sufficient for RpcFrame)

  const enumName = msg.name + upperFirst(oo.name);

  // --- Body enum ---
  lines.push(`public enum ${enumName}: Sendable {`);
  for (const f of oo.fields) {
    const camel = snakeToCamel(f.name);
    const caseName = escapeSwiftKeyword(camel);
    const msgDef = allMessages.find((m) => m.name === f.type);
    if (msgDef && msgDef.fields.length === 0 && msgDef.oneofs.length === 0) {
      lines.push(`    case ${caseName}`);
    } else {
      lines.push(`    case ${caseName}(${swiftType(f.type, enumNames)})`);
    }
  }
  lines.push('    case unknown');
  lines.push('}');
  lines.push('');

  // --- Parent struct ---
  lines.push(`public struct ${msg.name}: Codable, Sendable {`);

  // Non-oneof fields
  for (const f of msg.fields) {
    const camel = snakeToCamel(f.name);
    const isOpt = isOptionalField(f.type);
    const base = swiftType(f.type, enumNames);
    const type = f.repeated ? `[${base}]` : (isOpt ? `${base}?` : base);
    const def = f.repeated ? '[]' : swiftDefault(f.type, enumNames);
    lines.push(`    public var ${camel}: ${type} = ${def}`);
  }
  lines.push(`    public var ${oo.name}: ${enumName} = .unknown`);

  // Init
  lines.push('');
  const initParams: string[] = [];
  for (const f of msg.fields) {
    const camel = snakeToCamel(f.name);
    const isOpt = isOptionalField(f.type);
    const base = swiftType(f.type, enumNames);
    const type = f.repeated ? `[${base}]` : (isOpt ? `${base}?` : base);
    const def = f.repeated ? '[]' : swiftDefault(f.type, enumNames);
    initParams.push(`${camel}: ${type} = ${def}`);
  }
  initParams.push(`${oo.name}: ${enumName} = .unknown`);
  lines.push(`    public init(${initParams.join(', ')}) {`);
  for (const f of msg.fields) {
    const camel = snakeToCamel(f.name);
    lines.push(`        self.${camel} = ${camel}`);
  }
  lines.push(`        self.${oo.name} = ${oo.name}`);
  lines.push('    }');

  // CodingKeys
  lines.push('');
  lines.push('    enum CodingKeys: String, CodingKey {');
  for (const f of msg.fields) {
    lines.push(`        case ${escapeSwiftKeyword(snakeToCamel(f.name))}`);
  }
  for (const f of oo.fields) {
    lines.push(`        case ${escapeSwiftKeyword(snakeToCamel(f.name))}`);
  }
  lines.push('    }');

  // Custom decode
  lines.push('');
  lines.push('    public init(from decoder: Decoder) throws {');
  lines.push('        let container = try decoder.container(keyedBy: CodingKeys.self)');
  for (const f of msg.fields) {
    const camel = snakeToCamel(f.name);
    const key = escapeSwiftKeyword(camel);
    const st = swiftType(f.type, enumNames);
    lines.push(`        self.${camel} = (try? container.decode(${st}.self, forKey: .${key})) ?? ${swiftDefault(f.type, enumNames)}`);
  }
  // Decode oneofs
  for (let i = 0; i < oo.fields.length; i++) {
    const f = oo.fields[i];
    const camel = snakeToCamel(f.name);
    const caseName = escapeSwiftKeyword(camel);
    const msgDef = allMessages.find((m) => m.name === f.type);
    const isEmpty = msgDef && msgDef.fields.length === 0 && msgDef.oneofs.length === 0;
    const prefix = i === 0 ? 'if' : '} else if';

    if (isEmpty) {
      lines.push(`        ${prefix} container.contains(.${caseName}) {`);
      lines.push(`            self.${oo.name} = .${caseName}`);
    } else {
      lines.push(`        ${prefix} let v = try? container.decode(${swiftType(f.type, enumNames)}.self, forKey: .${caseName}) {`);
      lines.push(`            self.${oo.name} = .${caseName}(v)`);
    }
  }
  if (oo.fields.length > 0) {
    lines.push('        } else {');
    lines.push(`            self.${oo.name} = .unknown`);
    lines.push('        }');
  }
  lines.push('    }');

  // Custom encode
  lines.push('');
  lines.push('    public func encode(to encoder: Encoder) throws {');
  lines.push('        var container = encoder.container(keyedBy: CodingKeys.self)');
  for (const f of msg.fields) {
    const camel = snakeToCamel(f.name);
    const key = escapeSwiftKeyword(camel);
    lines.push(`        try container.encode(${camel}, forKey: .${key})`);
  }
  lines.push(`        switch ${oo.name} {`);
  for (const f of oo.fields) {
    const camel = snakeToCamel(f.name);
    const caseName = escapeSwiftKeyword(camel);
    const msgDef = allMessages.find((m) => m.name === f.type);
    const isEmpty = msgDef && msgDef.fields.length === 0 && msgDef.oneofs.length === 0;
    if (isEmpty) {
      lines.push(`        case .${caseName}:`);
      lines.push(`            try container.encode(${f.type}(), forKey: .${caseName})`);
    } else {
      lines.push(`        case .${caseName}(let v):`);
      lines.push(`            try container.encode(v, forKey: .${caseName})`);
    }
  }
  lines.push('        case .unknown: break');
  lines.push('        }');
  lines.push('    }');

  // JSON Data helpers
  lines.push('');
  lines.push('    public init(jsonUTF8Data data: Data) throws {');
  lines.push('        self = try JSONDecoder().decode(Self.self, from: data)');
  lines.push('    }');
  lines.push('');
  lines.push('    public func jsonUTF8Data() throws -> Data {');
  lines.push('        return try JSONEncoder().encode(self)');
  lines.push('    }');

  lines.push('}');
  return lines.join('\n');
}

function upperFirst(s: string): string {
  return s.charAt(0).toUpperCase() + s.slice(1);
}

// ---------------------------------------------------------------------------
// Service protocol generation
// ---------------------------------------------------------------------------

function generateServiceProtocol(svc: ServiceDef, proto: ProtoFile): string {
  const lines: string[] = [];
  lines.push(`public protocol ${svc.name}Provider: Sendable {`);

  for (const m of svc.methods) {
    const inputType = resolveTypeName(m.inputType, proto);
    const outputType = resolveTypeName(m.outputType, proto);
    const methodName = swiftMethodName(m.name);

    if (!m.clientStreaming && !m.serverStreaming) {
      lines.push(`    func ${methodName}(_ request: ${inputType}) async throws -> ${outputType}`);
    } else if (!m.clientStreaming && m.serverStreaming) {
      lines.push(`    func ${methodName}(_ request: ${inputType}) -> AsyncThrowingStream<${outputType}, Error>`);
    } else if (m.clientStreaming && !m.serverStreaming) {
      lines.push(`    func ${methodName}(_ requests: AsyncStream<${inputType}>) async throws -> ${outputType}`);
    } else {
      lines.push(`    func ${methodName}(_ requests: AsyncStream<${inputType}>) -> AsyncThrowingStream<${outputType}, Error>`);
    }
  }

  lines.push('}');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Dispatcher class generation
// ---------------------------------------------------------------------------

function generateDispatchError(): string {
  const lines: string[] = [];
  lines.push('public enum DispatchError: Error, Sendable {');
  lines.push('    case unknownMethod(String)');
  lines.push('    case missingRequestData');
  lines.push('}');
  return lines.join('\n');
}

function generateDispatcher(svc: ServiceDef, proto: ProtoFile): string {
  const lines: string[] = [];
  const fqServiceName = `${proto.package}.${svc.name}`;

  lines.push(`public final class ${svc.name}Dispatcher: ServiceDispatcher, @unchecked Sendable {`);
  lines.push(`    public let serviceName = "${fqServiceName}"`);
  lines.push(`    private let provider: any ${svc.name}Provider`);
  lines.push('');
  lines.push(`    public init(provider: any ${svc.name}Provider) {`);
  lines.push('        self.provider = provider');
  lines.push('    }');
  lines.push('');

  lines.push('    public func dispatch(');
  lines.push('        method: String,');
  lines.push('        messages: AsyncStream<Data>');
  lines.push('    ) async throws -> DispatchResult {');
  lines.push('        switch method {');

  for (const m of svc.methods) {
    const inputType = resolveTypeName(m.inputType, proto);
    const methodName = swiftMethodName(m.name);
    const fullMethodName = `${fqServiceName}/${m.name}`;

    lines.push(`        case "${fullMethodName}":`);

    if (!m.clientStreaming && !m.serverStreaming) {
      lines.push('            var requestData: Data?');
      lines.push('            for await data in messages { requestData = data; break }');
      lines.push('            guard let requestData else { throw DispatchError.missingRequestData }');
      lines.push(`            let request = try ${inputType}(jsonUTF8Data: requestData)`);
      lines.push(`            let response = try await provider.${methodName}(request)`);
      lines.push('            return .unary(try response.jsonUTF8Data())');
    } else if (!m.clientStreaming && m.serverStreaming) {
      lines.push('            var requestData: Data?');
      lines.push('            for await data in messages { requestData = data; break }');
      lines.push('            guard let requestData else { throw DispatchError.missingRequestData }');
      lines.push(`            let request = try ${inputType}(jsonUTF8Data: requestData)`);
      lines.push(`            let responseStream = provider.${methodName}(request)`);
      lines.push('            let mappedStream = AsyncThrowingStream<Data, Error> { continuation in');
      lines.push('                let task = Task {');
      lines.push('                    do {');
      lines.push('                        for try await response in responseStream {');
      lines.push('                            continuation.yield(try response.jsonUTF8Data())');
      lines.push('                        }');
      lines.push('                        continuation.finish()');
      lines.push('                    } catch {');
      lines.push('                        continuation.finish(throwing: error)');
      lines.push('                    }');
      lines.push('                }');
      lines.push('                continuation.onTermination = { _ in task.cancel() }');
      lines.push('            }');
      lines.push('            return .stream(mappedStream)');
    } else if (m.clientStreaming && !m.serverStreaming) {
      lines.push(`            let typedStream = AsyncStream<${inputType}> { continuation in`);
      lines.push('                Task {');
      lines.push('                    for await data in messages {');
      lines.push(`                        if let msg = try? ${inputType}(jsonUTF8Data: data) {`);
      lines.push('                            continuation.yield(msg)');
      lines.push('                        }');
      lines.push('                    }');
      lines.push('                    continuation.finish()');
      lines.push('                }');
      lines.push('            }');
      lines.push(`            let response = try await provider.${methodName}(typedStream)`);
      lines.push('            return .unary(try response.jsonUTF8Data())');
    } else {
      lines.push(`            let typedStream = AsyncStream<${inputType}> { continuation in`);
      lines.push('                Task {');
      lines.push('                    for await data in messages {');
      lines.push(`                        if let msg = try? ${inputType}(jsonUTF8Data: data) {`);
      lines.push('                            continuation.yield(msg)');
      lines.push('                        }');
      lines.push('                    }');
      lines.push('                    continuation.finish()');
      lines.push('                }');
      lines.push('            }');
      lines.push(`            let responseStream = provider.${methodName}(typedStream)`);
      lines.push('            let mappedStream = AsyncThrowingStream<Data, Error> { continuation in');
      lines.push('                let task = Task {');
      lines.push('                    do {');
      lines.push('                        for try await response in responseStream {');
      lines.push('                            continuation.yield(try response.jsonUTF8Data())');
      lines.push('                        }');
      lines.push('                        continuation.finish()');
      lines.push('                    } catch {');
      lines.push('                        continuation.finish(throwing: error)');
      lines.push('                    }');
      lines.push('                }');
      lines.push('                continuation.onTermination = { _ in task.cancel() }');
      lines.push('            }');
      lines.push('            return .stream(mappedStream)');
    }
  }

  lines.push('        default:');
  lines.push(`            throw DispatchError.unknownMethod(method)`);
  lines.push('        }');
  lines.push('    }');
  lines.push('');
  lines.push('}');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Indentation helper
// ---------------------------------------------------------------------------

function indent(text: string, level: number): string {
  const prefix = '    '.repeat(level);
  return text
    .split('\n')
    .map((line) => (line.length === 0 ? '' : prefix + line))
    .join('\n');
}
