/**
 * Kotlin code generator for the RPC bridge framework.
 *
 * Generates idiomatic Kotlin data classes with kotlinx-serialization-protobuf
 * annotations, service interfaces, and dispatcher classes from parsed .proto
 * file definitions.
 */

import type {
  ProtoFile,
  MessageDef,
  FieldDef,
  EnumDef,
  ServiceDef,
} from './parser.js';

// ---------------------------------------------------------------------------
// Proto-to-Kotlin type mapping
// ---------------------------------------------------------------------------

const PROTO_TO_KOTLIN: Record<string, string> = {
  string: 'String',
  bool: 'Boolean',
  bytes: 'ByteArray',
  int32: 'Int',
  int64: 'Long',
  uint32: 'UInt',
  uint64: 'ULong',
  sint32: 'Int',
  sint64: 'Long',
  fixed32: 'UInt',
  fixed64: 'ULong',
  sfixed32: 'Int',
  sfixed64: 'Long',
  float: 'Float',
  double: 'Double',
};

function kotlinType(protoType: string): string {
  return PROTO_TO_KOTLIN[protoType] ?? protoType;
}

function kotlinFieldType(field: FieldDef, allEnums: EnumDef[]): string {
  const base = kotlinType(field.type);
  if (field.repeated) return `List<${base}>`;
  if (field.optional) return `${base}?`;
  return base;
}

function defaultValue(field: FieldDef, allEnums: EnumDef[]): string {
  if (field.repeated) return 'emptyList()';
  if (field.optional) return 'null';
  const kt = kotlinType(field.type);
  switch (kt) {
    case 'String': return '""';
    case 'Boolean': return 'false';
    case 'ByteArray': return 'ByteArray(0)';
    case 'Int': return '0';
    case 'Long': return '0L';
    case 'UInt': return '0u';
    case 'ULong': return '0uL';
    case 'Float': return '0.0f';
    case 'Double': return '0.0';
    default:
      if (allEnums.some((e) => e.name === field.type)) {
        return `${kt}.fromValue(0)`;
      }
      return `${kt}()`;
  }
}

/** Proto types that map to 64-bit integers (Long/ULong), serialized as strings in JSON. */
const KOTLIN_INT64_TYPES = new Set([
  'int64', 'uint64', 'sint64', 'fixed64', 'sfixed64',
]);

function camelCase(name: string): string {
  return name.replace(/_([a-z])/g, (_, c) => c.toUpperCase());
}

function lowerFirst(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function upperFirst(name: string): string {
  return name.charAt(0).toUpperCase() + name.slice(1);
}

// ---------------------------------------------------------------------------
// Code generation
// ---------------------------------------------------------------------------

export function generateKotlin(proto: ProtoFile): string {
  const lines: string[] = [];
  const indent = (n: number) => '    '.repeat(n);

  function emit(depth: number, line: string) {
    if (line === '') {
      lines.push('');
    } else {
      lines.push(`${indent(depth)}${line}`);
    }
  }

  // File header
  emit(0, '@file:OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)');
  emit(0, '');
  emit(0, '// -----------------------------------------------------------------');
  emit(0, '// GENERATED CODE - DO NOT EDIT');
  emit(0, '//');
  emit(0, '// Generated by rpc-concept codegen from a .proto definition.');
  emit(0, '// Any manual changes will be overwritten on next generation.');
  emit(0, '// -----------------------------------------------------------------');
  emit(0, '');

  // Package
  if (proto.package) {
    emit(0, `package ${proto.package}`);
    emit(0, '');
  }

  // Imports
  emit(0, 'import android.util.Base64');
  emit(0, 'import com.rpcbridge.DispatchResult');
  emit(0, 'import com.rpcbridge.ServiceDispatcher');
  emit(0, 'import kotlinx.coroutines.flow.Flow');
  emit(0, 'import kotlinx.coroutines.flow.first');
  emit(0, 'import kotlinx.coroutines.flow.map');
  emit(0, 'import kotlinx.serialization.Serializable');
  emit(0, 'import kotlinx.serialization.protobuf.ProtoBuf');
  emit(0, 'import kotlinx.serialization.protobuf.ProtoNumber');
  emit(0, 'import org.json.JSONArray');
  emit(0, 'import org.json.JSONObject');
  emit(0, '');

  // Enums
  for (const enumDef of proto.enums) {
    emitEnum(emit, enumDef);
  }

  // Messages
  for (const msg of proto.messages) {
    emitMessage(emit, msg, proto.enums, proto.messages, proto.package);
  }

  // Services
  for (const svc of proto.services) {
    emitServiceInterface(emit, svc);
    emitDispatcher(emit, svc, proto.package);
  }

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Enum generation
// ---------------------------------------------------------------------------

function emitEnum(emit: (depth: number, line: string) => void, enumDef: EnumDef) {
  emit(0, `enum class ${enumDef.name}(val value: Int) {`);
  for (let i = 0; i < enumDef.values.length; i++) {
    const v = enumDef.values[i];
    const suffix = i < enumDef.values.length - 1 ? ',' : ';';
    emit(1, `${v.name}(${v.number})${suffix}`);
  }
  emit(0, '');
  emit(1, 'companion object {');
  emit(2, `fun fromValue(value: Int): ${enumDef.name} =`);
  emit(3, `entries.firstOrNull { it.value == value } ?: ${enumDef.values[0]?.name ?? 'throw IllegalArgumentException("Unknown enum value: $value")'}`);
  emit(1, '}');
  emit(0, '}');
  emit(0, '');
}

// ---------------------------------------------------------------------------
// Message data class generation (using kotlinx-serialization-protobuf)
// ---------------------------------------------------------------------------

function emitMessage(
  emit: (depth: number, line: string) => void,
  msg: MessageDef,
  allEnums: EnumDef[],
  allMessages: MessageDef[] = [],
  pkg: string = '',
) {
  if (msg.oneofs.length > 0) {
    emitOneofMessage(emit, msg, allEnums, allMessages, pkg);
    return;
  }

  const fields = msg.fields;

  emit(0, '@Serializable');
  if (fields.length === 0) {
    emit(0, `data class ${msg.name}(val _unused: Byte = 0) {`);
  } else {
    emit(0, `data class ${msg.name}(`);
    for (let i = 0; i < fields.length; i++) {
      const f = fields[i];
      const ktName = camelCase(f.name);
      const ktType = kotlinFieldType(f, allEnums);
      const defVal = defaultValue(f, allEnums);
      const comma = i < fields.length - 1 ? ',' : '';
      const deprecation = f.deprecated ? '@Deprecated("Field is deprecated") ' : '';
      emit(1, `${deprecation}@ProtoNumber(${f.number}) val ${ktName}: ${ktType} = ${defVal}${comma}`);
    }
    emit(0, ') {');
  }

  // encode()
  emit(0, '');
  emit(1, `fun encode(): ByteArray = ProtoBuf.encodeToByteArray(serializer(), this)`);

  // toJSON()
  emit(0, '');
  emit(1, 'fun toJSON(): JSONObject {');
  emit(2, 'val o = JSONObject()');
  for (const f of fields) {
    emitFieldToJSON(emit, f, allEnums);
  }
  emit(2, 'return o');
  emit(1, '}');

  // companion object with decode() and fromJSON()
  emit(0, '');
  emit(1, 'companion object {');
  emit(2, `fun decode(data: ByteArray): ${msg.name} = ProtoBuf.decodeFromByteArray(serializer(), data)`);
  emit(0, '');
  emit(2, `fun fromJSON(o: JSONObject): ${msg.name} {`);
  emit(3, `return ${msg.name}(`);
  for (let i = 0; i < fields.length; i++) {
    const f = fields[i];
    const comma = i < fields.length - 1 ? ',' : '';
    emitFieldFromJSON(emit, f, allEnums, comma);
  }
  emit(3, ')');
  emit(2, '}');
  emit(1, '}');
  emit(0, '}');
  emit(0, '');
}

// ---------------------------------------------------------------------------
// Oneof message generation
// ---------------------------------------------------------------------------

function emitOneofMessage(
  emit: (depth: number, line: string) => void,
  msg: MessageDef,
  allEnums: EnumDef[],
  allMessages: MessageDef[],
  pkg: string,
) {
  const oo = msg.oneofs[0]; // support the first oneof
  const sealedName = `${msg.name}${upperFirst(oo.name)}`;

  // Collect variant names to detect collisions with type names
  const variantNames = new Set(oo.fields.map(f => upperFirst(camelCase(f.name))));

  /** Qualify a type name if it collides with a sealed class variant name. */
  const qualifyType = (typeName: string): string => {
    const kt = kotlinType(typeName);
    return variantNames.has(kt) && pkg ? `${pkg}.${kt}` : kt;
  };

  // Sealed class for the oneof variants
  emit(0, `sealed class ${sealedName} {`);
  for (const f of oo.fields) {
    const caseName = upperFirst(camelCase(f.name));
    const isPrimitive = !!PROTO_TO_KOTLIN[f.type];
    const isEnum = allEnums.some(e => e.name === f.type);
    const msgDef = allMessages.find(m => m.name === f.type);
    const isEmpty = msgDef && msgDef.fields.length === 0 && msgDef.oneofs.length === 0;

    if (isEmpty) {
      emit(1, `data object ${caseName} : ${sealedName}()`);
    } else {
      const valType = isPrimitive || isEnum ? kotlinType(f.type) : qualifyType(f.type);
      emit(1, `data class ${caseName}(val value: ${valType}) : ${sealedName}()`);
    }
  }
  emit(1, `data object Unknown : ${sealedName}()`);
  emit(0, '}');
  emit(0, '');

  // Data class
  const fields = msg.fields;
  const allProps: string[] = [];
  for (const f of fields) {
    const ktName = camelCase(f.name);
    const ktType = kotlinFieldType(f, allEnums);
    const defVal = defaultValue(f, allEnums);
    allProps.push(`val ${ktName}: ${ktType} = ${defVal}`);
  }
  allProps.push(`@kotlinx.serialization.Transient val ${camelCase(oo.name)}: ${sealedName} = ${sealedName}.Unknown`);

  emit(0, '@Serializable');
  emit(0, `data class ${msg.name}(`);
  for (let i = 0; i < allProps.length; i++) {
    const comma = i < allProps.length - 1 ? ',' : '';
    emit(1, `${allProps[i]}${comma}`);
  }
  emit(0, ') {');

  // encode() - not fully supported for oneof with protobuf serialization
  emit(0, '');
  emit(1, `fun encode(): ByteArray = toJSON().toString().toByteArray()`);

  // toJSON()
  emit(0, '');
  emit(1, 'fun toJSON(): JSONObject {');
  emit(2, 'val o = JSONObject()');
  for (const f of fields) {
    emitFieldToJSON(emit, f, allEnums);
  }
  // Encode oneof
  emit(2, `when (${camelCase(oo.name)}) {`);
  for (const f of oo.fields) {
    const caseName = upperFirst(camelCase(f.name));
    const jsonKey = camelCase(f.name);
    const isPrimitive = !!PROTO_TO_KOTLIN[f.type];
    const isEnum = allEnums.some(e => e.name === f.type);
    const msgDef = allMessages.find(m => m.name === f.type);
    const isEmpty = msgDef && msgDef.fields.length === 0 && msgDef.oneofs.length === 0;
    const isBytes = f.type === 'bytes';
    const isInt64 = KOTLIN_INT64_TYPES.has(f.type);

    if (isEmpty) {
      emit(3, `is ${sealedName}.${caseName} -> o.put("${jsonKey}", JSONObject())`);
    } else if (isBytes) {
      emit(3, `is ${sealedName}.${caseName} -> o.put("${jsonKey}", Base64.encodeToString(${camelCase(oo.name)}.value, Base64.NO_WRAP))`);
    } else if (isInt64) {
      emit(3, `is ${sealedName}.${caseName} -> o.put("${jsonKey}", ${camelCase(oo.name)}.value.toString())`);
    } else if (isEnum) {
      emit(3, `is ${sealedName}.${caseName} -> o.put("${jsonKey}", ${camelCase(oo.name)}.value.value)`);
    } else if (isPrimitive) {
      emit(3, `is ${sealedName}.${caseName} -> o.put("${jsonKey}", ${camelCase(oo.name)}.value)`);
    } else {
      emit(3, `is ${sealedName}.${caseName} -> o.put("${jsonKey}", ${camelCase(oo.name)}.value.toJSON())`);
    }
  }
  emit(3, `is ${sealedName}.Unknown -> {}`);
  emit(2, '}');
  emit(2, 'return o');
  emit(1, '}');

  // companion object with decode() and fromJSON()
  emit(0, '');
  emit(1, 'companion object {');
  emit(2, `fun decode(data: ByteArray): ${msg.name} = fromJSON(JSONObject(String(data)))`);
  emit(0, '');
  emit(2, `fun fromJSON(o: JSONObject): ${msg.name} {`);

  // Decode regular fields
  const regularFieldExprs: string[] = [];
  for (const f of fields) {
    regularFieldExprs.push(fieldFromJSONExpr(f, allEnums));
  }

  // Decode oneof
  emit(3, `val ${camelCase(oo.name)}: ${sealedName} = run {`);
  for (let i = 0; i < oo.fields.length; i++) {
    const f = oo.fields[i];
    const caseName = upperFirst(camelCase(f.name));
    const jsonKey = camelCase(f.name);
    const kt = kotlinType(f.type);
    const qkt = qualifyType(f.type);
    const isPrimitive = !!PROTO_TO_KOTLIN[f.type];
    const isEnum = allEnums.some(e => e.name === f.type);
    const msgDef = allMessages.find(m => m.name === f.type);
    const isEmpty = msgDef && msgDef.fields.length === 0 && msgDef.oneofs.length === 0;
    const isBytes = f.type === 'bytes';
    const isInt64 = KOTLIN_INT64_TYPES.has(f.type);
    const prefix = i === 0 ? 'if' : '} else if';

    if (isEmpty) {
      emit(4, `${prefix} (o.has("${jsonKey}")) {`);
      emit(5, `${sealedName}.${caseName}`);
    } else if (isBytes) {
      emit(4, `${prefix} (o.has("${jsonKey}")) {`);
      emit(5, `${sealedName}.${caseName}(Base64.decode(o.getString("${jsonKey}"), Base64.NO_WRAP))`);
    } else if (isInt64) {
      const conv = kt === 'ULong' ? 'toULong()' : 'toLong()';
      emit(4, `${prefix} (o.has("${jsonKey}")) {`);
      emit(5, `${sealedName}.${caseName}(o.getString("${jsonKey}").${conv})`);
    } else if (isEnum) {
      emit(4, `${prefix} (o.has("${jsonKey}")) {`);
      emit(5, `${sealedName}.${caseName}(${qkt}.fromValue(o.getInt("${jsonKey}")))`);
    } else if (isPrimitive) {
      emit(4, `${prefix} (o.has("${jsonKey}")) {`);
      let getter: string;
      switch (kt) {
        case 'String': getter = `o.getString("${jsonKey}")`; break;
        case 'Boolean': getter = `o.getBoolean("${jsonKey}")`; break;
        case 'Int': getter = `o.getInt("${jsonKey}")`; break;
        case 'UInt': getter = `o.getInt("${jsonKey}").toUInt()`; break;
        case 'Float': getter = `o.getDouble("${jsonKey}").toFloat()`; break;
        case 'Double': getter = `o.getDouble("${jsonKey}")`; break;
        default: getter = `o.get("${jsonKey}") as ${kt}`; break;
      }
      emit(5, `${sealedName}.${caseName}(${getter})`);
    } else {
      emit(4, `${prefix} (o.has("${jsonKey}")) {`);
      emit(5, `${sealedName}.${caseName}(${qkt}.fromJSON(o.getJSONObject("${jsonKey}")))`);
    }
  }
  if (oo.fields.length > 0) {
    emit(4, '} else {');
    emit(5, `${sealedName}.Unknown`);
    emit(4, '}');
  } else {
    emit(4, `${sealedName}.Unknown`);
  }
  emit(3, '}');

  emit(3, `return ${msg.name}(`);
  for (const expr of regularFieldExprs) {
    emit(4, `${expr},`);
  }
  emit(4, `${camelCase(oo.name)} = ${camelCase(oo.name)},`);
  emit(3, ')');
  emit(2, '}');
  emit(1, '}');
  emit(0, '}');
  emit(0, '');
}

/** Returns the expression for reading a field from JSON (for use in constructor call). */
function fieldFromJSONExpr(f: FieldDef, allEnums: EnumDef[]): string {
  const ktName = camelCase(f.name);
  const kt = kotlinType(f.type);
  const isInt64 = KOTLIN_INT64_TYPES.has(f.type);
  const isBytes = f.type === 'bytes';
  const isMessage = !PROTO_TO_KOTLIN[f.type] && !allEnums.some(e => e.name === f.type);
  const isEnum = allEnums.some(e => e.name === f.type);

  if (f.repeated) {
    if (isMessage) return `${ktName} = o.optJSONArray("${ktName}")?.let { arr -> (0 until arr.length()).map { ${kt}.fromJSON(arr.getJSONObject(it)) } } ?: emptyList()`;
    if (isInt64) { const conv = kt === 'ULong' ? 'toULong()' : 'toLong()'; return `${ktName} = o.optJSONArray("${ktName}")?.let { arr -> (0 until arr.length()).map { arr.getString(it).${conv} } } ?: emptyList()`; }
    if (isBytes) return `${ktName} = o.optJSONArray("${ktName}")?.let { arr -> (0 until arr.length()).map { Base64.decode(arr.getString(it), Base64.NO_WRAP) } } ?: emptyList()`;
    if (isEnum) return `${ktName} = o.optJSONArray("${ktName}")?.let { arr -> (0 until arr.length()).map { ${kt}.fromValue(arr.getInt(it)) } } ?: emptyList()`;
    let getter: string;
    switch (kt) {
      case 'String': getter = 'getString'; break;
      case 'Boolean': getter = 'getBoolean'; break;
      case 'Int': getter = 'getInt'; break;
      case 'UInt': getter = 'getInt'; break;
      case 'Float': getter = 'getDouble'; break;
      case 'Double': getter = 'getDouble'; break;
      default: getter = 'get'; break;
    }
    const cast = kt === 'UInt' ? '.toUInt()' : kt === 'Float' ? '.toFloat()' : '';
    return `${ktName} = o.optJSONArray("${ktName}")?.let { arr -> (0 until arr.length()).map { arr.${getter}(it)${cast} } } ?: emptyList()`;
  }

  if (f.optional) {
    if (isMessage) return `${ktName} = o.optJSONObject("${ktName}")?.let { ${kt}.fromJSON(it) }`;
    if (isInt64) { const conv = kt === 'ULong' ? 'toULong()' : 'toLong()'; return `${ktName} = o.opt("${ktName}")?.let { v -> when (v) { is String -> v.${conv}; is Number -> v.toLong()${kt === 'ULong' ? '.toULong()' : ''} ; else -> null } }`; }
    if (isBytes) return `${ktName} = o.optString("${ktName}", null)?.let { Base64.decode(it, Base64.NO_WRAP) }`;
    if (isEnum) return `${ktName} = if (o.has("${ktName}")) ${kt}.fromValue(o.getInt("${ktName}")) else null`;
    switch (kt) {
      case 'String': return `${ktName} = o.optString("${ktName}", null)`;
      case 'Boolean': return `${ktName} = if (o.has("${ktName}")) o.getBoolean("${ktName}") else null`;
      case 'Int': return `${ktName} = if (o.has("${ktName}")) o.getInt("${ktName}") else null`;
      case 'UInt': return `${ktName} = if (o.has("${ktName}")) o.getInt("${ktName}").toUInt() else null`;
      case 'Float': return `${ktName} = if (o.has("${ktName}")) o.getDouble("${ktName}").toFloat() else null`;
      case 'Double': return `${ktName} = if (o.has("${ktName}")) o.getDouble("${ktName}") else null`;
      default: return `${ktName} = o.opt("${ktName}")`;
    }
  }

  // Non-optional
  if (isMessage) return `${ktName} = o.optJSONObject("${ktName}")?.let { ${kt}.fromJSON(it) } ?: ${kt}()`;
  if (isInt64) { const conv = kt === 'ULong' ? 'toULong()' : 'toLong()'; const defVal = kt === 'ULong' ? '0uL' : '0L'; return `${ktName} = o.opt("${ktName}")?.let { v -> when (v) { is String -> v.${conv}; is Number -> v.toLong()${kt === 'ULong' ? '.toULong()' : ''}; else -> ${defVal} } } ?: ${defVal}`; }
  if (isBytes) return `${ktName} = o.optString("${ktName}", null)?.let { Base64.decode(it, Base64.NO_WRAP) } ?: ByteArray(0)`;
  if (isEnum) return `${ktName} = if (o.has("${ktName}")) ${kt}.fromValue(o.getInt("${ktName}")) else ${kt}.fromValue(0)`;
  switch (kt) {
    case 'String': return `${ktName} = o.optString("${ktName}", "")`;
    case 'Boolean': return `${ktName} = o.optBoolean("${ktName}", false)`;
    case 'Int': return `${ktName} = o.optInt("${ktName}", 0)`;
    case 'UInt': return `${ktName} = o.optInt("${ktName}", 0).toUInt()`;
    case 'Float': return `${ktName} = o.optDouble("${ktName}", 0.0).toFloat()`;
    case 'Double': return `${ktName} = o.optDouble("${ktName}", 0.0)`;
    default: return `${ktName} = o.opt("${ktName}") as? ${kt} ?: ${defaultValue(f, allEnums)}`;
  }
}

// ---------------------------------------------------------------------------
// Field JSON serialization helpers
// ---------------------------------------------------------------------------

function emitFieldToJSON(
  emit: (depth: number, line: string) => void,
  f: FieldDef,
  allEnums: EnumDef[],
) {
  if (f.deprecated) return;
  const ktName = camelCase(f.name);
  const isInt64 = KOTLIN_INT64_TYPES.has(f.type);
  const isBytes = f.type === 'bytes';
  const isMessage = !PROTO_TO_KOTLIN[f.type] && !allEnums.some(e => e.name === f.type);
  const isEnum = allEnums.some(e => e.name === f.type);

  if (f.repeated) {
    emit(2, `if (${ktName}.isNotEmpty()) {`);
    emit(3, `val arr = JSONArray()`);
    if (isMessage) {
      emit(3, `${ktName}.forEach { arr.put(it.toJSON()) }`);
    } else if (isInt64) {
      emit(3, `${ktName}.forEach { arr.put(it.toString()) }`);
    } else if (isBytes) {
      emit(3, `${ktName}.forEach { arr.put(Base64.encodeToString(it, Base64.NO_WRAP)) }`);
    } else if (isEnum) {
      emit(3, `${ktName}.forEach { arr.put(it.value) }`);
    } else {
      emit(3, `${ktName}.forEach { arr.put(it) }`);
    }
    emit(3, `o.put("${ktName}", arr)`);
    emit(2, '}');
  } else if (f.optional) {
    if (isMessage) {
      emit(2, `${ktName}?.let { o.put("${ktName}", it.toJSON()) }`);
    } else if (isInt64) {
      emit(2, `${ktName}?.let { o.put("${ktName}", it.toString()) }`);
    } else if (isBytes) {
      emit(2, `${ktName}?.let { o.put("${ktName}", Base64.encodeToString(it, Base64.NO_WRAP)) }`);
    } else if (isEnum) {
      emit(2, `${ktName}?.let { o.put("${ktName}", it.value) }`);
    } else {
      emit(2, `${ktName}?.let { o.put("${ktName}", it) }`);
    }
  } else {
    if (isMessage) {
      emit(2, `o.put("${ktName}", ${ktName}.toJSON())`);
    } else if (isInt64) {
      const kt = kotlinType(f.type);
      const defZero = kt === 'ULong' ? '0uL' : '0L';
      emit(2, `if (${ktName} != ${defZero}) o.put("${ktName}", ${ktName}.toString())`);
    } else if (isBytes) {
      emit(2, `if (${ktName}.isNotEmpty()) o.put("${ktName}", Base64.encodeToString(${ktName}, Base64.NO_WRAP))`);
    } else if (isEnum) {
      emit(2, `if (${ktName}.value != 0) o.put("${ktName}", ${ktName}.value)`);
    } else {
      const kt = kotlinType(f.type);
      let zeroCheck: string;
      switch (kt) {
        case 'String': zeroCheck = `${ktName}.isNotEmpty()`; break;
        case 'Boolean': zeroCheck = `${ktName}`; break;
        case 'Int': case 'UInt': zeroCheck = `${ktName} != ${kt === 'UInt' ? '0u' : '0'}`; break;
        case 'Float': zeroCheck = `${ktName} != 0.0f`; break;
        case 'Double': zeroCheck = `${ktName} != 0.0`; break;
        default: zeroCheck = `true`; break;
      }
      emit(2, `if (${zeroCheck}) o.put("${ktName}", ${ktName})`);
    }
  }
}

function emitFieldFromJSON(
  emit: (depth: number, line: string) => void,
  f: FieldDef,
  allEnums: EnumDef[],
  comma: string,
) {
  if (f.deprecated) return;
  emit(4, `${fieldFromJSONExpr(f, allEnums)}${comma}`);
}

// ---------------------------------------------------------------------------
// Service interface generation
// ---------------------------------------------------------------------------

function emitServiceInterface(
  emit: (depth: number, line: string) => void,
  svc: ServiceDef,
) {
  emit(0, `interface ${svc.name} {`);
  for (const m of svc.methods) {
    emit(0, '');
    const reqType = kotlinType(m.inputType);
    const respType = kotlinType(m.outputType);

    if (!m.clientStreaming && !m.serverStreaming) {
      // Unary
      emit(1, `suspend fun ${lowerFirst(m.name)}(request: ${reqType}): ${respType}`);
    } else if (!m.clientStreaming && m.serverStreaming) {
      // Server streaming
      emit(1, `fun ${lowerFirst(m.name)}(request: ${reqType}): Flow<${respType}>`);
    } else if (m.clientStreaming && !m.serverStreaming) {
      // Client streaming
      emit(1, `suspend fun ${lowerFirst(m.name)}(requests: Flow<${reqType}>): ${respType}`);
    } else {
      // Bidi streaming
      emit(1, `fun ${lowerFirst(m.name)}(requests: Flow<${reqType}>): Flow<${respType}>`);
    }
  }
  emit(0, '}');
  emit(0, '');
}

// ---------------------------------------------------------------------------
// Dispatcher generation
// ---------------------------------------------------------------------------

function emitDispatcher(
  emit: (depth: number, line: string) => void,
  svc: ServiceDef,
  pkg: string,
) {
  const dispatcherName = `${svc.name}Dispatcher`;
  const serviceQualifier = pkg ? `${pkg}.${svc.name}` : svc.name;

  emit(0, `class ${dispatcherName}(private val service: ${svc.name}) : ServiceDispatcher {`);
  emit(0, '');
  emit(1, `override val serviceName = "${serviceQualifier}"`);
  emit(0, '');

  // JSON-based dispatch method
  emit(1, '/** Dispatch using JSON-encoded byte arrays (proto3 JSON mapping). */');
  emit(1, 'override suspend fun dispatchJSON(method: String, messages: Flow<ByteArray>): DispatchResult {');
  emit(2, 'return when (method) {');

  for (const m of svc.methods) {
    const methodFullName = `"${serviceQualifier}/${m.name}"`;
    const reqType = kotlinType(m.inputType);
    const methodName = lowerFirst(m.name);

    if (!m.clientStreaming && !m.serverStreaming) {
      emit(3, `${methodFullName} -> {`);
      emit(4, `val request = ${reqType}.fromJSON(JSONObject(String(messages.first())))`);
      emit(4, `val response = service.${methodName}(request)`);
      emit(4, 'DispatchResult.Unary(response.toJSON().toString().toByteArray())');
      emit(3, '}');
    } else if (!m.clientStreaming && m.serverStreaming) {
      emit(3, `${methodFullName} -> {`);
      emit(4, `val request = ${reqType}.fromJSON(JSONObject(String(messages.first())))`);
      emit(4, `val responseFlow = service.${methodName}(request)`);
      emit(4, 'DispatchResult.Stream(responseFlow.map { it.toJSON().toString().toByteArray() })');
      emit(3, '}');
    } else if (m.clientStreaming && !m.serverStreaming) {
      emit(3, `${methodFullName} -> {`);
      emit(4, `val typedStream = messages.map { ${reqType}.fromJSON(JSONObject(String(it))) }`);
      emit(4, `val response = service.${methodName}(typedStream)`);
      emit(4, 'DispatchResult.Unary(response.toJSON().toString().toByteArray())');
      emit(3, '}');
    } else {
      emit(3, `${methodFullName} -> {`);
      emit(4, `val typedStream = messages.map { ${reqType}.fromJSON(JSONObject(String(it))) }`);
      emit(4, `val responseFlow = service.${methodName}(typedStream)`);
      emit(4, 'DispatchResult.Stream(responseFlow.map { it.toJSON().toString().toByteArray() })');
      emit(3, '}');
    }
  }

  emit(3, 'else -> throw IllegalArgumentException("Unknown method: $method")');
  emit(2, '}');
  emit(1, '}');
  emit(0, '');

  // Original protobuf dispatch
  emit(1, 'override suspend fun dispatch(method: String, messages: Flow<ByteArray>): DispatchResult {');
  emit(2, 'return when (method) {');

  for (const m of svc.methods) {
    const methodFullName = `"${serviceQualifier}/${m.name}"`;
    const reqType = kotlinType(m.inputType);
    const methodName = lowerFirst(m.name);

    if (!m.clientStreaming && !m.serverStreaming) {
      // Unary
      emit(3, `${methodFullName} -> {`);
      emit(4, `val request = ${reqType}.decode(messages.first())`);
      emit(4, `val response = service.${methodName}(request)`);
      emit(4, 'DispatchResult.Unary(response.encode())');
      emit(3, '}');
    } else if (!m.clientStreaming && m.serverStreaming) {
      // Server streaming
      emit(3, `${methodFullName} -> {`);
      emit(4, `val request = ${reqType}.decode(messages.first())`);
      emit(4, `val responseFlow = service.${methodName}(request)`);
      emit(4, 'DispatchResult.Stream(responseFlow.map { it.encode() })');
      emit(3, '}');
    } else if (m.clientStreaming && !m.serverStreaming) {
      // Client streaming
      emit(3, `${methodFullName} -> {`);
      emit(4, `val typedStream = messages.map { ${reqType}.decode(it) }`);
      emit(4, `val response = service.${methodName}(typedStream)`);
      emit(4, 'DispatchResult.Unary(response.encode())');
      emit(3, '}');
    } else {
      // Bidi streaming
      emit(3, `${methodFullName} -> {`);
      emit(4, `val typedStream = messages.map { ${reqType}.decode(it) }`);
      emit(4, `val responseFlow = service.${methodName}(typedStream)`);
      emit(4, 'DispatchResult.Stream(responseFlow.map { it.encode() })');
      emit(3, '}');
    }
  }

  emit(3, 'else -> throw IllegalArgumentException("Unknown method: $method")');
  emit(2, '}');
  emit(1, '}');
  emit(0, '}');
  emit(0, '');
}
