/**
 * Swift code generator for the RPC bridge framework.
 *
 * Generates typealiases to protoc-gen-swift types, service provider protocols
 * with async/await, and dispatcher classes for routing raw bytes to typed
 * handler methods.
 *
 * Message structs and protobuf encoding are handled by protoc-gen-swift.
 * This generator only produces the RPC glue code.
 */

import type {
  ProtoFile,
  ServiceDef,
} from './parser.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export function generateSwift(proto: ProtoFile): string {
  const lines: string[] = [];
  const emit = (line = '') => lines.push(line);
  const emitBlock = (block: string) => {
    for (const l of block.split('\n')) {
      lines.push(l);
    }
  };

  const namespace = swiftNamespace(proto.package);

  // File header
  emit('// DO NOT EDIT.');
  emit(`// Generated by rpc-bridge-codegen from package "${proto.package}".`);
  emit('// Any manual changes will be overwritten on the next generation run.');
  emit('');
  emit('import Foundation');
  emit('import SwiftProtobuf');
  emit('import RpcBridge');
  emit('');

  // Namespace enum (acts as a Swift namespace)
  emit(`// MARK: - ${namespace}`);
  emit('');
  emit(`public enum ${namespace} {`);

  // Typealiases for enums
  for (const enumDef of proto.enums) {
    emit('');
    emit(`    public typealias ${enumDef.name} = ${protocSwiftName(proto.package, enumDef.name)}`);
  }

  // Typealiases for messages
  for (const msg of proto.messages) {
    emit('');
    emit(`    public typealias ${msg.name} = ${protocSwiftName(proto.package, msg.name)}`);
  }

  // Dispatch error type (emitted once for all services)
  if (proto.services.length > 0) {
    emit('');
    emitBlock(indent(generateDispatchError(), 1));
  }

  // Services
  for (const svc of proto.services) {
    emit('');
    emitBlock(indent(generateServiceProtocol(svc, proto), 1));
    emit('');
    emitBlock(indent(generateDispatcher(svc, proto), 1));
  }

  emit('}'); // close namespace enum

  return lines.join('\n') + '\n';
}

// ---------------------------------------------------------------------------
// Naming helpers
// ---------------------------------------------------------------------------

/** Convert a proto package like "demo.hello.v1" to "DemoHelloV1". */
function swiftNamespace(pkg: string): string {
  return pkg
    .split('.')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/**
 * Convert a proto package + message name to the protoc-gen-swift generated name.
 * e.g. package "demo.hello.v1" + message "HelloRequest" = "Demo_Hello_V1_HelloRequest"
 */
function protocSwiftName(pkg: string, typeName: string): string {
  const prefix = pkg
    .split('.')
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('_');
  return `${prefix}_${typeName}`;
}

/** Convert a proto method name (PascalCase) to Swift camelCase. */
function swiftMethodName(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

/** Resolve a proto type reference to the short name used inside the namespace enum. */
function resolveTypeName(protoType: string, proto: ProtoFile): string {
  const pkg = proto.package;
  if (protoType.startsWith(pkg + '.')) {
    return protoType.slice(pkg.length + 1);
  }
  return protoType;
}

// ---------------------------------------------------------------------------
// Service protocol generation
// ---------------------------------------------------------------------------

function generateServiceProtocol(svc: ServiceDef, proto: ProtoFile): string {
  const lines: string[] = [];
  lines.push(`public protocol ${svc.name}Provider: Sendable {`);

  for (const m of svc.methods) {
    const inputType = resolveTypeName(m.inputType, proto);
    const outputType = resolveTypeName(m.outputType, proto);
    const methodName = swiftMethodName(m.name);

    if (!m.clientStreaming && !m.serverStreaming) {
      lines.push(`    func ${methodName}(_ request: ${inputType}) async throws -> ${outputType}`);
    } else if (!m.clientStreaming && m.serverStreaming) {
      lines.push(`    func ${methodName}(_ request: ${inputType}) -> AsyncThrowingStream<${outputType}, Error>`);
    } else if (m.clientStreaming && !m.serverStreaming) {
      lines.push(`    func ${methodName}(_ requests: AsyncStream<${inputType}>) async throws -> ${outputType}`);
    } else {
      lines.push(`    func ${methodName}(_ requests: AsyncStream<${inputType}>) -> AsyncThrowingStream<${outputType}, Error>`);
    }
  }

  lines.push('}');
  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Dispatcher class generation
// ---------------------------------------------------------------------------

function generateDispatchError(): string {
  const lines: string[] = [];
  lines.push('public enum DispatchError: Error, Sendable {');
  lines.push('    case unknownMethod(String)');
  lines.push('    case missingRequestData');
  lines.push('}');
  return lines.join('\n');
}

function generateDispatcher(svc: ServiceDef, proto: ProtoFile): string {
  const lines: string[] = [];
  const fqServiceName = `${proto.package}.${svc.name}`;

  lines.push(`public final class ${svc.name}Dispatcher: ServiceDispatcher, @unchecked Sendable {`);
  lines.push(`    public let serviceName = "${fqServiceName}"`);
  lines.push(`    private let provider: any ${svc.name}Provider`);
  lines.push('');
  lines.push(`    public init(provider: any ${svc.name}Provider) {`);
  lines.push('        self.provider = provider');
  lines.push('    }');
  lines.push('');

  // JSON dispatch method
  lines.push('    /// Dispatch using JSON-encoded Data (proto3 JSON mapping).');
  lines.push('    /// SwiftProtobuf handles int64-as-string and bytes-as-base64 automatically.');
  lines.push('    public func dispatchJSON(');
  lines.push('        method: String,');
  lines.push('        messages: AsyncStream<Data>');
  lines.push('    ) async throws -> DispatchResult {');
  lines.push('        switch method {');

  for (const m of svc.methods) {
    const inputType = resolveTypeName(m.inputType, proto);
    const methodName = swiftMethodName(m.name);
    const fullMethodName = `${fqServiceName}/${m.name}`;

    lines.push(`        case "${fullMethodName}":`);

    if (!m.clientStreaming && !m.serverStreaming) {
      lines.push('            var requestData: Data?');
      lines.push('            for await data in messages { requestData = data; break }');
      lines.push('            guard let requestData else { throw DispatchError.missingRequestData }');
      lines.push(`            let request = try ${inputType}(jsonUTF8Data: requestData)`);
      lines.push(`            let response = try await provider.${methodName}(request)`);
      lines.push('            return .unary(try response.jsonUTF8Data())');
    } else if (!m.clientStreaming && m.serverStreaming) {
      lines.push('            var requestData: Data?');
      lines.push('            for await data in messages { requestData = data; break }');
      lines.push('            guard let requestData else { throw DispatchError.missingRequestData }');
      lines.push(`            let request = try ${inputType}(jsonUTF8Data: requestData)`);
      lines.push(`            let responseStream = provider.${methodName}(request)`);
      lines.push('            let mappedStream = AsyncThrowingStream<Data, Error> { continuation in');
      lines.push('                Task {');
      lines.push('                    do {');
      lines.push('                        for try await response in responseStream {');
      lines.push('                            continuation.yield(try response.jsonUTF8Data())');
      lines.push('                        }');
      lines.push('                        continuation.finish()');
      lines.push('                    } catch {');
      lines.push('                        continuation.finish(throwing: error)');
      lines.push('                    }');
      lines.push('                }');
      lines.push('            }');
      lines.push('            return .stream(mappedStream)');
    } else if (m.clientStreaming && !m.serverStreaming) {
      lines.push(`            let typedStream = AsyncStream<${inputType}> { continuation in`);
      lines.push('                Task {');
      lines.push('                    for await data in messages {');
      lines.push(`                        if let msg = try? ${inputType}(jsonUTF8Data: data) {`);
      lines.push('                            continuation.yield(msg)');
      lines.push('                        }');
      lines.push('                    }');
      lines.push('                    continuation.finish()');
      lines.push('                }');
      lines.push('            }');
      lines.push(`            let response = try await provider.${methodName}(typedStream)`);
      lines.push('            return .unary(try response.jsonUTF8Data())');
    } else {
      lines.push(`            let typedStream = AsyncStream<${inputType}> { continuation in`);
      lines.push('                Task {');
      lines.push('                    for await data in messages {');
      lines.push(`                        if let msg = try? ${inputType}(jsonUTF8Data: data) {`);
      lines.push('                            continuation.yield(msg)');
      lines.push('                        }');
      lines.push('                    }');
      lines.push('                    continuation.finish()');
      lines.push('                }');
      lines.push('            }');
      lines.push(`            let responseStream = provider.${methodName}(typedStream)`);
      lines.push('            let mappedStream = AsyncThrowingStream<Data, Error> { continuation in');
      lines.push('                Task {');
      lines.push('                    do {');
      lines.push('                        for try await response in responseStream {');
      lines.push('                            continuation.yield(try response.jsonUTF8Data())');
      lines.push('                        }');
      lines.push('                        continuation.finish()');
      lines.push('                    } catch {');
      lines.push('                        continuation.finish(throwing: error)');
      lines.push('                    }');
      lines.push('                }');
      lines.push('            }');
      lines.push('            return .stream(mappedStream)');
    }
  }

  lines.push('        default:');
  lines.push(`            throw DispatchError.unknownMethod(method)`);
  lines.push('        }');
  lines.push('    }');
  lines.push('');

  // Protobuf binary dispatch method (existing)
  lines.push('    public func dispatch(');
  lines.push('        method: String,');
  lines.push('        messages: AsyncStream<Data>');
  lines.push('    ) async throws -> DispatchResult {');
  lines.push('        switch method {');

  for (const m of svc.methods) {
    const inputType = resolveTypeName(m.inputType, proto);
    const methodName = swiftMethodName(m.name);
    const fullMethodName = `${fqServiceName}/${m.name}`;

    lines.push(`        case "${fullMethodName}":`);

    if (!m.clientStreaming && !m.serverStreaming) {
      // Unary
      lines.push('            var requestData: Data?');
      lines.push('            for await data in messages { requestData = data; break }');
      lines.push('            guard let requestData else { throw DispatchError.missingRequestData }');
      lines.push(`            let request = try ${inputType}(serializedBytes: requestData)`);
      lines.push(`            let response = try await provider.${methodName}(request)`);
      lines.push('            return .unary(try response.serializedData())');
    } else if (!m.clientStreaming && m.serverStreaming) {
      // Server streaming
      lines.push('            var requestData: Data?');
      lines.push('            for await data in messages { requestData = data; break }');
      lines.push('            guard let requestData else { throw DispatchError.missingRequestData }');
      lines.push(`            let request = try ${inputType}(serializedBytes: requestData)`);
      lines.push(`            let responseStream = provider.${methodName}(request)`);
      lines.push('            let mappedStream = AsyncThrowingStream<Data, Error> { continuation in');
      lines.push('                Task {');
      lines.push('                    do {');
      lines.push('                        for try await response in responseStream {');
      lines.push('                            continuation.yield(try response.serializedData())');
      lines.push('                        }');
      lines.push('                        continuation.finish()');
      lines.push('                    } catch {');
      lines.push('                        continuation.finish(throwing: error)');
      lines.push('                    }');
      lines.push('                }');
      lines.push('            }');
      lines.push('            return .stream(mappedStream)');
    } else if (m.clientStreaming && !m.serverStreaming) {
      // Client streaming
      lines.push(`            let typedStream = AsyncStream<${inputType}> { continuation in`);
      lines.push('                Task {');
      lines.push('                    for await data in messages {');
      lines.push(`                        if let msg = try? ${inputType}(serializedBytes: data) {`);
      lines.push('                            continuation.yield(msg)');
      lines.push('                        }');
      lines.push('                    }');
      lines.push('                    continuation.finish()');
      lines.push('                }');
      lines.push('            }');
      lines.push(`            let response = try await provider.${methodName}(typedStream)`);
      lines.push('            return .unary(try response.serializedData())');
    } else {
      // Bidi streaming
      lines.push(`            let typedStream = AsyncStream<${inputType}> { continuation in`);
      lines.push('                Task {');
      lines.push('                    for await data in messages {');
      lines.push(`                        if let msg = try? ${inputType}(serializedBytes: data) {`);
      lines.push('                            continuation.yield(msg)');
      lines.push('                        }');
      lines.push('                    }');
      lines.push('                    continuation.finish()');
      lines.push('                }');
      lines.push('            }');
      lines.push(`            let responseStream = provider.${methodName}(typedStream)`);
      lines.push('            let mappedStream = AsyncThrowingStream<Data, Error> { continuation in');
      lines.push('                Task {');
      lines.push('                    do {');
      lines.push('                        for try await response in responseStream {');
      lines.push('                            continuation.yield(try response.serializedData())');
      lines.push('                        }');
      lines.push('                        continuation.finish()');
      lines.push('                    } catch {');
      lines.push('                        continuation.finish(throwing: error)');
      lines.push('                    }');
      lines.push('                }');
      lines.push('            }');
      lines.push('            return .stream(mappedStream)');
    }
  }

  lines.push('        default:');
  lines.push(`            throw DispatchError.unknownMethod(method)`);
  lines.push('        }');
  lines.push('    }');
  lines.push('}');

  return lines.join('\n');
}

// ---------------------------------------------------------------------------
// Indentation helper
// ---------------------------------------------------------------------------

function indent(text: string, level: number): string {
  const prefix = '    '.repeat(level);
  return text
    .split('\n')
    .map((line) => (line.length === 0 ? '' : prefix + line))
    .join('\n');
}
